### ISSUE TITLE
❌ Error:  Issue  with ts linter on compile (using typescript) 

### ISSUE THREAD

**Issue by jpalala** [mayajs/router#19]
See https://gist.github.com/jpalala/e40d69d3b2e56f51e32aaa70c96307b2

The TSC / tslint is having trouble compiling on [line 8](https://github.com/jpalala/mayarouter-test/blob/main/src/server.ts#L8):

```javascript
// src/server.ts#L8
app.add([{
  path: '/',
  GET: () => 'Hello World!', //Line 8
}]);
```

**Comment by macign** [comment]
@jpalala  What version of `@mayajs/router` you are using?

**Comment by jpalala** [comment]
based on package-lock, its "version": "0.3.0",

**Comment by macign** [comment]
Can you try `npm i @mayajs/router@next` and run it again.
